version: 0.0
os: linux
files:
  - source: app/scripts/
    destination: /home/ec2-user/app/scripts/

permissions:
  - object: scripts/start_server.sh
    mode: 755

hooks:
  AfterInstall:
    - location: app/scripts/start_server.sh
      timeout: 300
      runas: ec2-user